In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Stock Prices Data Set.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 497472 entries, 0 to 497471
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   symbol  497472 non-null  str
 1   date    497472 non-null  str
 2   open    497461 non-null  float64
 3   high    497464 non-null  float64
 4   low     497464 non-null  float64
 5   close   497472 non-null  float64
 6   volume  497472 non-null  int64
dtypes: float64(4), int64(1), str(2)
memory usage: 26.6 MB

In [4]:
df.head()

  symbol        date      open      high       low     close    volume
0    AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943
1   AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957
2    AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711
3   ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061
4    ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391

In [5]:
df.tail()

       symbol        date    open    high     low   close   volume
497467    XYL  2017-12-29   68.53   68.80   67.92   68.20  1046677
497468    YUM  2017-12-29   82.64   82.71   81.59   81.61  1347613
497469    ZBH  2017-12-29  121.75  121.95  120.62  120.67  1023624
497470   ZION  2017-12-29   51.28   51.55   50.81   50.83  1261916
497471    ZTS  2017-12-29   72.55   72.76   72.04   72.04  1704122

In [6]:
df.describe()

,open,high,low,close,volume
count,497461.000000,497464.000000,497464.000000,497472.000000,4.974720e+05
mean,86.352275,87.132562,85.552467,86.369082,4.253611e+06
std,101.471228,102.312062,100.570957,101.472407,8.232139e+06
min,1.620000,1.690000,1.500000,1.590000,0.000000e+00
25%,41.690000,42.090000,41.280000,41.703750,1.080166e+06
50%,64.970000,65.560000,64.353700,64.980000,2.084896e+06
75%,98.410000,99.230000,97.580000,98.420000,4.271928e+06
max,2044.000000,2067.990000,2035.110000,2049.000000,6.182376e+08

In [7]:
df.isnull().sum()

symbol     0
date       0
open      11
high       8
low        8
close      0
volume     0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dtypes

symbol        str
date          str
open      float64
high      float64
low       float64
close     float64
volume      int64
dtype: object

In [12]:
df= df.sort_values(by ='date')

In [13]:
df.reset_index(drop=True, inplace=True)

In [16]:
numeric_cols = ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']

In [19]:
df.shape

(497472, 7)

In [20]:
df.columns

Index(['symbol', 'date', 'open', 'high', 'low', 'close', 'volume'], dtype='str')

In [21]:
df.drop([1,3])

       symbol        date    open    high      low   close   volume
0         AAL  2014-01-02   25.07   25.82   25.060   25.36  8998943
2         NUE  2014-01-02   53.29   53.38   52.510   52.73  1611326
4        NTAP  2014-01-02   41.01   41.01   40.415   40.42  2427140
5         NSC  2014-01-02   92.33   92.59   91.070   91.31  1321650
6         NRG  2014-01-02   28.74   28.78   28.500   28.58  3896367
...       ...         ...     ...     ...      ...     ...      ...
497467    EMR  2017-12-29   70.04   70.21   69.690   69.69  1848874
497468    EMN  2017-12-29   93.71   93.76   92.550   92.64   632351
497469     EL  2017-12-29  127.80  128.13  127.200  127.24   805149
497470   EVHC  2017-12-29   34.70   35.09   34.530   34.56  1471045
497471    ZTS  2017-12-29   72.55   72.76   72.040   72.04  1704122

[497470 rows x 7 columns]

In [4]:
df.to_csv("cleaned_stock_price.csv", index=False)